### ISSUE TITLE
El pollo se desborda de la pantalla

### ISSUE THREAD

**Issue by felixicaza** [ManzDev/twitch-diplopollo#2]
Cuando el cuello del pollo crece demasiado llega a desbordarse de la pantalla. Adjunto clip del momento en el que el pollo se desborda en el stream.

https://github.com/ManzDev/twitch-diplopollo/assets/38303370/fda60126-d355-46c4-b649-7dd8c4890282

**Comment by ManzDev** [comment]
¡Solucionado! ¡Gracias @felixicaza!
